export const Theme = {
    DANGER_COLOR: '#e53935',
    GREY_COLOR: '#757575',
    MAIN_COLOR: '#3949ab',
    WHITE_COLOR: '#ffffff',
    BLACK_COLOR: '#000000',
    PADDING_HORIZONTAL: 30,
    PADDING_VERTICAL: 20
}

export const ActionType = {
    ADD_TODO: 'ADD_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    UPDATE_TODO: 'UPDATE_TODO',
    CHANGE_SCREEN: 'CHANGE_SCREEN',
    SHOW_LOADER: 'SHOW_LOADER',
    HIDE_LOADER: 'HIDE_LOADER',
    SHOW_ERROR: 'SHOW_ERROR',
    CLEAR_ERROR: 'CLEAR_ERROR',
    FETCH_TODO: 'FETCH_TODO'
}
